# **Multiple Linear Regression**
Gajitos, Jude B.
BSCS 3B

# **1. Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# **2. Creating a Synthetic Dataset**

In [ ]:
np.random.seed()
x = np.random.rand(100, 3)
y = x[:,0] * 15000 + x[:,1] * 100000 + x[:,2] * 50000 + 50000

# **3. Converting to a DataFrame**

In [ ]:
data = pd.DataFrame(x, columns = ['Size', 'Bedrooms', 'Age'])
data['Price'] = y

X_train, X_test, y_train, y_test, = train_test_split(x,y, test_size = 0.2, random_state = 42)
data.head()

Size  Bedrooms       Age          Price
0  0.137028  0.444344  0.744400  133709.828801
1  0.090562  0.097146  0.032602   62703.144203
2  0.017551  0.603679  0.482604  134761.410460
3  0.858556  0.543430  0.699129  152177.734039
4  0.492774  0.149323  0.909518  117799.831448

# **4. Initializing the Model**

In [ ]:
model = LinearRegression()

# **5. Fitting the Model**

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

# **6. Making Prediction**

In [ ]:
y_predict = model.predict(X_test)
print(X_test)
print(y_predict)

[[0.87545878 0.11038866 0.45356566]
 [0.12971144 0.0990046  0.11249581]
 [0.71771498 0.38056179 0.52249049]
 [0.19456684 0.53411167 0.70395282]
 [0.50578808 0.0048738  0.37729144]
 [0.55904845 0.24211413 0.50755937]
 [0.33995132 0.77382019 0.99526935]
 [0.69565457 0.74846344 0.78107237]
 [0.01499171 0.39628967 0.28925183]
 [0.13702795 0.44434418 0.74439984]
 [0.74609498 0.0779791  0.82720633]
 [0.21089638 0.06423158 0.91582009]
 [0.2439304  0.26233564 0.76718594]
 [0.9897961  0.08859847 0.96762047]
 [0.02815767 0.09792646 0.2458241 ]
 [0.49277381 0.14932324 0.90951801]
 [0.8273803  0.74493374 0.20275994]
 [0.41719119 0.05964118 0.00258002]
 [0.77364859 0.3989516  0.81391537]
 [0.75913023 0.09368477 0.70416582]]
[ 96849.03102626  67470.92140974 124946.42836532 141527.31073804
  76938.77380183 107975.10783264 182244.75623847 174334.7805674
 104316.43451847 133709.82880099 110349.65088711 105377.60831105
 118251.81682725 122087.81180757  72506.21628294 117799.83144774
 147042.07487297  62

# **7. Calculating the Mean Squared Error**

In [ ]:
mse = mean_squared_error(y_test, y_predict)
print("Mean Squared Error:", mse)

Mean Squared Error: 3.1763735522036263e-22


# **8. Predicting the Price of a New House**

In [ ]:
new_house = [[0.5, 2, 10]]
predicted_price = model.predict(new_house)
print(f"Predicted: {predicted_price[0]}")

Predicted: 757500.0000000002
